/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 enterijer3.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/enterijer3.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-3.048, -2.308, -2.116]} rotation={[0, 1.508, 0]} scale={0.773}>
        <group position={[0.76, 0, -0.048]} rotation={[-Math.PI / 2, 0, 0]} scale={67.151}>
          <mesh geometry={nodes.Couch_Medium1_1.geometry} material={materials.Couch_Blue} />
          <mesh geometry={nodes.Couch_Medium1_2.geometry} material={materials.Black} />
        </group>
      </group>
      <group position={[3.024, -1.986, -1.952]} rotation={[0, -1.489, 0]} scale={0.47}>
        <group position={[0.006, -0.634, -0.077]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Drawer_2_1.geometry} material={materials.Wood} />
          <mesh geometry={nodes.Drawer_2_2.geometry} material={materials.Wood_Light} />
          <mesh geometry={nodes.Drawer_2_3.geometry} material={materials.Wood_Dark} />
        </group>
      </group>
      <group position={[1.225, -2.189, 0.514]} rotation={[0, -1.571, 0]} scale={0.268}>
        <mesh geometry={nodes.Bolt.geometry} material={materials['Material.007']} position={[0.786, 2.049, -0.203]} rotation={[0, 0, -1.734]} scale={0.013} />
        <mesh geometry={nodes.Bolt001.geometry} material={materials['Material.007']} position={[0.782, 1.991, 0.152]} rotation={[0, 0, -1.734]} scale={0.013} />
        <mesh geometry={nodes.New_Object.geometry} material={materials['Material.004']} position={[0, 1.546, 0]} scale={4.635} />
        <mesh geometry={nodes.New_Object001.geometry} material={materials['Material.003']} position={[0, 1.531, 0]} scale={4.635} />
        <mesh geometry={nodes.New_Object002.geometry} material={materials['Material.003']} position={[0, 1.546, 0]} scale={4.635} />
      </group>
      <group position={[1.358, -2.203, -1.201]} rotation={[-1.571, -1.559, -1.571]} scale={0.268}>
        <mesh geometry={nodes.Bolt002.geometry} material={materials['Material.007']} position={[0.782, 1.991, 0.152]} rotation={[0, 0, -1.734]} scale={0.013} />
        <mesh geometry={nodes.Bolt003.geometry} material={materials['Material.007']} position={[0.786, 2.049, -0.203]} rotation={[0, 0, -1.734]} scale={0.013} />
        <mesh geometry={nodes.New_Object003.geometry} material={materials['Material.003']} position={[0, 1.546, 0]} scale={4.635} />
        <mesh geometry={nodes.New_Object004.geometry} material={materials['Material.003']} position={[0, 1.531, 0]} scale={4.635} />
        <mesh geometry={nodes.New_Object005.geometry} material={materials['Material.004']} position={[0, 1.546, 0]} scale={4.635} />
      </group>
      <group position={[-1.301, -2.177, -0.908]} rotation={[1.571, 1.566, -1.571]} scale={0.268}>
        <mesh geometry={nodes.Bolt004.geometry} material={materials['Material.007']} position={[0.782, 1.991, 0.152]} rotation={[0, 0, -1.734]} scale={0.013} />
        <mesh geometry={nodes.Bolt005.geometry} material={materials['Material.007']} position={[0.786, 2.049, -0.203]} rotation={[0, 0, -1.734]} scale={0.013} />
        <mesh geometry={nodes.New_Object006.geometry} material={materials['Material.003']} position={[0, 1.546, 0]} scale={4.635} />
        <mesh geometry={nodes.New_Object007.geometry} material={materials['Material.003']} position={[0, 1.531, 0]} scale={4.635} />
        <mesh geometry={nodes.New_Object008.geometry} material={materials['Material.004']} position={[0, 1.546, 0]} scale={4.635} />
      </group>
      <group position={[-1.261, -2.129, 0.581]} rotation={[1.571, 1.535, -1.571]} scale={0.268}>
        <mesh geometry={nodes.Bolt006.geometry} material={materials['Material.007']} position={[0.782, 1.991, 0.152]} rotation={[0, 0, -1.734]} scale={0.013} />
        <mesh geometry={nodes.Bolt007.geometry} material={materials['Material.007']} position={[0.786, 2.049, -0.203]} rotation={[0, 0, -1.734]} scale={0.013} />
        <mesh geometry={nodes.New_Object009.geometry} material={materials['Material.003']} position={[0, 1.546, 0]} scale={4.635} />
        <mesh geometry={nodes.New_Object010.geometry} material={materials['Material.003']} position={[0, 1.531, 0]} scale={4.635} />
        <mesh geometry={nodes.New_Object011.geometry} material={materials['Material.004']} position={[0, 1.546, 0]} scale={4.635} />
      </group>
      <group position={[3.089, -1.68, -1.887]} rotation={[Math.PI, -0.086, Math.PI]}>
        <mesh geometry={nodes['Legs_Cube005-Mesh'].geometry} material={materials.Tone2} />
        <mesh geometry={nodes['Legs_Cube005-Mesh_1'].geometry} material={materials.Tone1} />
        <mesh geometry={nodes['Legs_Cube005-Mesh_2'].geometry} material={materials.Screen} />
        <mesh geometry={nodes['Legs_Cube005-Mesh_3'].geometry} material={materials.Screw} />
      </group>
      <mesh geometry={nodes.RubberFigPottedPlant_mesh.geometry} material={materials.RubberFigPottedPlant_mat} position={[-2.762, -2.189, 2.89]} scale={0.185} />
      <group position={[0, 0.088, 0]}>
        <mesh geometry={nodes.Cube013.geometry} material={materials['standing_picture_frame_02_artwork.001']} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials['standing_picture_frame_02.001']} />
        <mesh geometry={nodes.Cube013_2.geometry} material={materials['standing_picture_frame_02_glass.001']} />
      </group>
      <mesh geometry={nodes.ceramic_vase_01.geometry} material={materials.ceramic_vase_01} position={[2.114, -2.008, 3.393]} scale={0.743} />
      <mesh geometry={nodes.outdoor_table_chair_set_01_chair_01.geometry} material={materials.outdoor_table_chair_set_01_chair} position={[-0.091, 0.088, 0]} rotation={[0, 0.243, 0]} />
      <mesh geometry={nodes.outdoor_table_chair_set_01_table.geometry} material={materials.outdoor_table_chair_set_01_table} position={[-0.091, 0.088, 0]} />
      <mesh geometry={nodes.outdoor_table_chair_set_01_chair_02.geometry} material={materials.outdoor_table_chair_set_01_chair} position={[-0.091, 0.088, 0]} rotation={[0, 0.268, 0]} />
      <group position={[0.111, 0.087, -0.203]}>
        <mesh geometry={nodes.ChessRook003.geometry} material={materials.chess_set_pieces_white} />
        <mesh geometry={nodes.ChessRook003_1.geometry} material={materials.chess_set_board} />
        <mesh geometry={nodes.ChessRook003_2.geometry} material={materials.chess_set_pieces_black} />
      </group>
      <mesh geometry={nodes.RubberFigPottedPlant_mesh001.geometry} material={materials.RubberFigPottedPlant_mat} position={[-2.762, -2.189, 2.89]} scale={0.185} />
      <mesh geometry={nodes.Text002.geometry} material={nodes.Text002.material} position={[-1.514, 0.316, -1.18]} rotation={[Math.PI / 2, 0, 0]} scale={0.423} />
      <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} position={[-1.204, 0.398, -1.269]} rotation={[Math.PI / 2, 0, 0]} scale={0.423} />
      <mesh geometry={nodes.Text003.geometry} material={nodes.Text003.material} position={[-1.202, 0.414, -1.295]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.423} />
      <mesh geometry={nodes.strelica.geometry} material={nodes.strelica.material} position={[2.124, -0.274, 1.945]} rotation={[0, 0, -1.578]} scale={[0.121, 0.484, 0.121]} />
      <group position={[0.006, 0.092, 0]} scale={[4.2, 2.5, 4.2]}>
        <mesh geometry={nodes.Cube011.geometry} material={materials.pod} />
        <mesh geometry={nodes.Cube011_1.geometry} material={materials.zid} />
        <mesh geometry={nodes.Cube011_2.geometry} material={materials.plafon} />
        <mesh geometry={nodes.Cube011_3.geometry} material={materials.zid2} />
        <mesh geometry={nodes.Cube011_4.geometry} material={materials.pod2} />
      </group>
      <mesh geometry={nodes.nogare.geometry} material={materials['Material.005']} position={[-0.009, -1.425, -0.267]} scale={[0.6, 0.025, 1.5]} />
      <mesh geometry={nodes.ploca.geometry} material={nodes.ploca.material} position={[0, -1.369, -0.263]} scale={[0.7, 0.02, 1.6]} />
      <mesh geometry={nodes.ram.geometry} material={materials['Material.005']} position={[3.095, 1.353, 1.036]} rotation={[0, 0, -Math.PI / 2]} scale={[0.6, 0.025, 1.5]} />
      <mesh geometry={nodes.zidovi.geometry} material={materials['Dark Iron']} position={[-3.101, -1.955, 1.194]} rotation={[0, 0.659, 0]} scale={1.191}>
        <mesh geometry={nodes.grede.geometry} material={materials['Material.002']} position={[0.001, -0.155, 0.212]} scale={[0.352, 0.008, 0.008]} />
        <mesh geometry={nodes.nogice.geometry} material={materials['Material.001']} position={[-0.003, -0.229, -0.007]} rotation={[0.069, -0.664, -3.098]} />
        <mesh geometry={nodes.platno.geometry} material={materials['Laces 02']} position={[0, -0.159, 0.222]} scale={[0.324, 0.001, 0.001]} />
      </mesh>
      <mesh geometry={nodes.nogare002.geometry} material={nodes.nogare002.material} position={[1.316, -1.983, 0.375]} rotation={[0.127, 0, 0.158]} scale={[0.021, 0.208, 0.021]} />
      <mesh geometry={nodes.nogare001.geometry} material={nodes.nogare001.material} position={[1.452, -1.998, -1.34]} rotation={[0.127, 0, 0.158]} scale={[0.021, 0.208, 0.021]} />
      <mesh geometry={nodes.nogare003.geometry} material={nodes.nogare003.material} position={[-1.205, -1.977, -1.035]} rotation={[0.127, 0, 0.158]} scale={[0.021, 0.208, 0.021]} />
      <mesh geometry={nodes.nogare004.geometry} material={nodes.nogare004.material} position={[-1.154, -1.932, 0.454]} rotation={[0.127, 0, 0.158]} scale={[0.021, 0.208, 0.021]} />
      <mesh geometry={nodes.podOkvir.geometry} material={materials.okvir} position={[-4.062, -0.142, 0.663]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[1.286, 1, 1.492]} />
      <mesh geometry={nodes.okvir001.geometry} material={materials.prozori} position={[-1.242, -0.379, 4]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1.928, 0.674, 2.608]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.012']} position={[-1.253, -0.345, 4]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1, 0.673, 1]} />
      <mesh geometry={nodes.instagram.geometry} material={materials['Material.009']} position={[1.63, 0.436, -1.246]} rotation={[0, 1.571, 0]} scale={[0.15, 0.25, 0.25]} />
      <mesh geometry={nodes.krugovi.geometry} material={nodes.krugovi.material} position={[1.63, 0.436, -1.426]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.1, 0.03, 0.1]} />
      <mesh geometry={nodes.luster001.geometry} material={nodes.luster001.material} position={[0.368, 0.729, 4]} scale={0.645} />
      <mesh geometry={nodes.kabal.geometry} material={nodes.kabal.material} position={[0.007, 1.549, -0.051]} scale={[0.005, 0.9, 0.005]} />
      <mesh geometry={nodes.treasure_chest_bottom.geometry} material={materials['treasure_chest.001']} position={[2.844, -1.92, 0.51]} rotation={[0, -1.571, 0]} />
      <mesh geometry={nodes.treasure_chest_handle_left.geometry} material={materials['treasure_chest.001']} position={[2.832, -1.877, 0.043]} rotation={[0, -1.571, 0]} />
      <mesh geometry={nodes.treasure_chest_handle_right.geometry} material={materials['treasure_chest.001']} position={[2.832, -1.877, 0.977]} rotation={[0, -1.571, 0]} />
      <mesh geometry={nodes.treasure_chest_lid.geometry} material={materials['treasure_chest.001']} position={[2.821, -1.632, 0.51]} rotation={[0, -1.571, 0]} />
      <mesh geometry={nodes.treasure_chest_lock.geometry} material={materials['treasure_chest.001']} position={[2.577, -1.796, 0.51]} rotation={[0, -1.571, 0]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.011']} position={[-1.141, 0.369, -0.342]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.010']} position={[-1.059, 0.148, 0.704]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Text001.geometry} material={nodes.Text001.material} position={[0.345, 0.374, 0.01]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.BezierCurve.geometry} material={nodes.BezierCurve.material} position={[2.825, -0.829, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.625} />
      <mesh geometry={nodes.BezierCurve001.geometry} material={nodes.BezierCurve001.material} position={[2.825, -0.829, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.625} />
    </group>
  )
}

useGLTF.preload('/enterijer3.glb')
